### ISSUE TITLE
"You need to sign in or sign up before continuing" or "socket hang up"

### ISSUE THREAD

**Issue by lucasvianav** [jeangnc/us-visa-bot#2]
Whenever I try to run the bot I get either of the following errors. Is this expected or should it be able to login on the first few attempts?
```
[2023-03-07T14:45:29.397Z] Logging in
Error: You need to sign in or sign up before continuing.
    at handleErrors (file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:107:11)
    at file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:85:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:25:20)
```
```
[2023-03-07T14:52:43.321Z] Logging in
FetchError: request to https://ais.usvisa-info.com/pt-br/niv/schedule/?????/appointment/days/??.json?appointments[expedite]=false failed, reason: socket hang up
    at ClientRequest.<anonymous> (file:///home/lucas/hdd/Downloads/us-visa-bot/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:512:28)
    at TLSSocket.socketOnEnd (node:_http_client:520:9)
    at TLSSocket.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}
```

**Comment by Salybn** [comment]
> Whenever I try to run the bot I get either of the following errors. Is this expected or should it be able to login on the first few attempts?
> 
> ```
> [2023-03-07T14:45:29.397Z] Logging in
> Error: You need to sign in or sign up before continuing.
>     at handleErrors (file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:107:11)
>     at file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:85:16
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async main (file:///home/lucas/hdd/Downloads/us-visa-bot/index.js:25:20)
> ```
> 
> ```
> [2023-03-07T14:52:43.321Z] Logging in
> FetchError: request to https://ais.usvisa-info.com/pt-br/niv/schedule/47403791/appointment/days/60.json?appointments[expedite]=false failed, reason: socket hang up
>     at ClientRequest.<anonymous> (file:///home/lucas/hdd/Downloads/us-visa-bot/node_modules/node-fetch/src/index.js:108:11)
>     at ClientRequest.emit (node:events:512:28)
>     at TLSSocket.socketOnEnd (node:_http_client:520:9)
>     at TLSSocket.emit (node:events:524:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   type: 'system',
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET',
>   erroredSysCall: undefined
> }
> ```

Hi, Please can you help me to use the bot , I need an urgent us visa appointment and the first available one is on May 2024 :(

**Comment by jeangnc** [comment]
Hey Lucas, let me help you.

Do these failures happen immediately after you start the process? Also, can you make sure you exported all the variables?

P.s.: I took the liberty to hide your schedule ID from the logs you posted.

**Comment by jeangnc** [comment]
@lucasvianav, please notice that once in a while, you'll see `You need to sign in or sign up before continuing.` on your logs, but then the app will automatically sign in again and keep working.

**Comment by jeangnc** [comment]
@lucasvianav, please notice that once in a while, you'll see `You need to sign in or sign up before continuing.` on your logs, but then the app will automatically sign in again and keep working. 

The second problem may happen when you make too many requests in a short period, not only through the script but also in your web browser.

You're IP will get blocked for a few hours, and then the script will resume its work.

P.s.: I took the liberty to hide your schedule ID from the logs you posted.

**Comment by jeangnc** [comment]
What worked for me was setting up an AWS EC2 instance (you can run one for [free](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all) for a few days) and leaving the script running so my browser wouldn't be blocked and the script wouldn't suddenly stop when my machine slept (I needed to get a fast visa). It takes a while to trust the script, but once you do, you'll forget about it and follow the email notifications.

**Comment by lucasvianav** [comment]
hey! can't believe I doxed myself, thanks for the heads up. 

I see, thought it wasn't working because I didn't get to see any other logs along it's execution, but makes sense that it'd take a while and my IP must've been blocked first.

I ended up getting a reschedule manually, but thanks anyway :)
