### ISSUE TITLE
Blocked all available dates.

### ISSUE THREAD

**Issue by kerny-** [jeangnc/us-visa-bot#9]
I had quite a few dates that were available in August and September, but when I started constantly updating the site the dates disappeared and now I see only this message "_No existen citas disponibles en la ubicación seleccionada. Por favor vuelva a intentar después_". Could they block me during my elevated activity? And is there any way to protect the script from blocking?

**Comment by qomhmd** [comment]
Did you find the answer of your issue?

**Comment by vicdup** [comment]
Same questiom, @qomhmd  @kerny- what's the update?

**Comment by soroushoraki** [comment]
Did any of you find your answer? @kerny- @qomhmd @vicdup 
I've been running the code for 8 hours. After this, it got stuck in the "login" process. I tried logging in manually after this, but the "reschedule" page does not open for me.
Is it possible that they blocked my account from rescheduling?
